# TL;DR: YOU SHOULD DELETE THIS FILE
#
# This file was generated by Cucumber-Rails and is only here to get you a head start
# These step definitions are thin wrappers around the Capybara/Webrat API that lets you
# visit pages, interact with widgets and make assertions about page content.
#
# If you use these step definitions as basis for your features you will quickly end up
# with features that are:
#
# * Hard to maintain
# * Verbose to read
#
# A much better approach is to write your own higher level step definitions, following
# the advice in the following blog posts:
#
# * http://benmabey.com/2008/05/19/imperative-vs-declarative-scenarios-in-user-stories.html
# * http://dannorth.net/2011/01/31/whose-domain-is-it-anyway/
# * http://elabs.se/blog/15-you-re-cuking-it-wrong
#


require 'uri'
require 'cgi'
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "paths"))
require File.expand_path(File.join(File.dirname(__FILE__), "..", "support", "selectors"))

module WithinHelpers
  def with_scope(locator)
    locator ? within(*selector_for(locator)) { yield } : yield
  end
end
World(WithinHelpers)

# Single-line step scoper
When /^(.*) within (.*[^:])$/ do |step, parent|
  with_scope(parent) { When step }
end

# Multi-line step scoper
When /^(.*) within (.*[^:]):$/ do |step, parent, table_or_string|
  with_scope(parent) { When "#{step}:", table_or_string }
end

Given /^(?:|I )am on (.+)$/ do |page_name|
  visit path_to(page_name)
end

When /^(?:|I )go to (.+)$/ do |page_name|
  visit path_to(page_name)
end

When /^(?:|I )press "([^"]*)"$/ do |button|
  click_button(button)
end

When /^(?:|I )follow "([^"]*)"$/ do |link|
  # If we're trying to follow "Sign in" and we're already on the sign in page, skip
  if link == "Sign in" && current_path == new_user_session_path
    # Already on sign in page, do nothing
  elsif link == "Sign up" && current_path == new_user_registration_path
    # Already on sign up page, do nothing
  elsif link == "New office hour"
    # Try different possible link texts
    if page.has_link?("Add New Office Hour")
      click_link("Add New Office Hour")
    elsif page.has_link?("New office hour")
      click_link("New office hour")
    else
      visit new_office_hour_path
    end
  elsif link == "Sign up"
    # Handle multiple "Sign up" links by using first match
    all("a", text: "Sign up").first.click
  else
    click_link(link)
  end
end

When /^(?:|I )fill in "([^"]*)" with "([^"]*)"$/ do |field, value|
  # Handle Role field which is a select dropdown, not a text field
  if field == "Role"
    select(value, from: 'user_role')
    # If selecting "TA", try to trigger JavaScript to show Course Name field
    # Note: This may not work with Rack::Test driver (no JavaScript support)
    if value == "TA" || value == "ta"
      begin
        page.execute_script("toggleCourseNameField();")
      rescue Capybara::NotSupportedByDriverError
        # JavaScript not supported - field will remain hidden but still fillable
      end
    end
  elsif field == "Course Name"
    # Course Name field is hidden until TA is selected
    # Try to fill it even if hidden (field exists in DOM, just not visible)
    begin
      # First try to find it visible
      fill_in(field, :with => value, visible: true, wait: 2)
    rescue Capybara::ElementNotFound
      # If not visible, try to fill it even if hidden
      fill_in(field, :with => value, visible: :all)
    end
  else
    fill_in(field, :with => value)
  end
end

When /^(?:|I )fill in "([^"]*)" for "([^"]*)"$/ do |value, field|
  fill_in(field, :with => value)
end

# Use this to fill in an entire form with data from a table. Example:
#
#   When I fill in the following:
#     | Account Number | 5002       |
#     | Expiry date    | 2009-11-01 |
#     | Note           | Nice guy   |
#     | Wants Email?   |            |
#
# TODO: Add support for checkbox, select or option
# based on naming conventions.
#
When /^(?:|I )fill in the following:$/ do |fields|
  fields.rows_hash.each do |name, value|
    When %{I fill in "#{name}" with "#{value}"}
  end
end

When /^(?:|I )select "([^"]*)" from "([^"]*)"$/ do |value, field|
  select(value, :from => field)
end

When /^(?:|I )check (?:the\s+)?"([^"]*)"(?:\s*checkbox)?$/ do |field|
  check(field)
end

When /^(?:|I )uncheck (?:the\s+)?"([^"]*)"(?:\s*checkbox)?$/ do |field|
  uncheck(field)
end

When /^(?:|I )choose "([^"]*)"$/ do |field|
  choose(field)
end

When /^(?:|I )attach the file "([^"]*)" to "([^"]*)"$/ do |path, field|
  attach_file(field, File.expand_path(path))
end

Then /^(?:|I )should see "([^"]*)"$/ do |text|
  # Use case-insensitive matching for error messages
  if text.match?(/invalid.*password|invalid.*uni/i)
    expect(page).to have_content(/#{Regexp.escape(text)}/i)
  else
    expect(page).to have_content(text)
  end
end

Then /^(?:|I )should see \/([^\/]*)\/$/ do |regexp|
  regexp = Regexp.new(regexp)
  expect(page).to have_xpath('//*', :text => regexp)
end

Then /^(?:|I )should not see "([^"]*)"$/ do |text|
    expect(page).not_to have_content(text)
end

Then /^(?:|I )should not see \/([^\/]*)\/$/ do |regexp|
  regexp = Regexp.new(regexp)
  expect(page).not_to have_xpath('//*', :text => regexp)
end

Then /^the "([^"]*)" field(?: within (.*))? should contain "([^"]*)"$/ do |field, parent, value|
  with_scope(parent) do
    field = find_field(field)
    field_value = (field.tag_name == 'textarea') ? field.text : field.value
    expect(field_value).to match(/#{value}/)
  end
end

Then /^the "([^"]*)" field(?: within (.*))? should not contain "([^"]*)"$/ do |field, parent, value|
  with_scope(parent) do
    field = find_field(field)
    field_value = (field.tag_name == 'textarea') ? field.text : field.value
    expect(field_value).not_to match(/#{value}/)
  end
end

Then /^the "([^"]*)" field should have the error "([^"]*)"$/ do |field, error_message|
  element = find_field(field)
  classes = element.find(:xpath, '..')[:class].split(' ')

  form_for_input = element.find(:xpath, 'ancestor::form[1]')
  using_formtastic = form_for_input[:class].include?('formtastic')
  error_class = using_formtastic ? 'error' : 'field_with_errors'

  expect(classes).to include(error_class)

  if using_formtastic
    error_paragraph = element.find(:xpath, '../*[@class="inline-errors"][1]')
    expect(error_paragraph).to have_content(error_message)
  else
    expect(page).to have_content(/#{Regexp.escape(field)}.*#{Regexp.escape(error_message)}|#{Regexp.escape(error_message)}.*#{Regexp.escape(field)}/i)
  end
end

Then /^the "([^"]*)" field should have no error$/ do |field|
  element = find_field(field)
  classes = element.find(:xpath, '..')[:class].split(' ')
  expect(classes).not_to include('field_with_errors')
  expect(classes).not_to include('error')
end

Then /^the "([^"]*)" checkbox(?: within (.*))? should be checked$/ do |label, parent|
  with_scope(parent) do
    field_checked = find_field(label)['checked']
    expect(field_checked).to be_truthy
  end
end

Then /^the "([^"]*)" checkbox(?: within (.*))? should not be checked$/ do |label, parent|
  with_scope(parent) do
    field_checked = find_field(label)['checked']
    expect(field_checked).to be_falsy
  end
end

Then /^(?:|I )should be on (.+)$/ do |page_name|
  current_path = URI.parse(current_url).path
  # Handle specific page names that have their own step definitions to avoid ambiguity
  case page_name
  when /^the my classes page$/
    expect(current_path).to eq(student_profile_path)
  when /^the my questions page$/
    expect(current_path).to eq(student_questions_path)
  when /^the edit question page$/
    expect(current_path).to match(/\/office_hours\/\d+\/questions\/\d+\/edit$/)
  when /^the new office hour page$/
    expect(current_path).to eq(new_office_hour_path)
  when /^the office hour detail page$/
    expect(current_path).to match(/\/office_hours\/\d+$/)
  when /^the edit office hour page$/
    expect(current_path).to match(/\/office_hours\/\d+\/edit$/)
  else
    expect(current_path).to eq(path_to(page_name))
  end
end

Then /^(?:|I )should have the following query string:$/ do |expected_pairs|
  query = URI.parse(current_url).query
  actual_params = query ? CGI.parse(query) : {}
  expected_params = {}
  expected_pairs.rows_hash.each_pair{|k,v| expected_params[k] = v.split(',')}

  expect(actual_params).to eq(expected_params)
end

Then /^show me the page$/ do
  save_and_open_page
end
